In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
import joblib

df = pd.read_csv("logements_synthetiques.csv")
df.head()

,titre,type,ville,quartier,surface,nb_chambres,nb_salons,nb_salles_de_bains,prix
0,Studio à Cocody,studio,Abidjan,Cocody,26,0,1,1,120000
1,Studio à Marcory,studio,Abidjan,Marcory,39,0,1,1,155000
2,Studio à Adjamé,studio,Abidjan,Adjamé,36,0,1,1,70000
3,Studio à Plateau,studio,Abidjan,Plateau,24,0,1,1,120000
4,Studio à Abobo,studio,Abidjan,Abobo,35,0,1,1,55000

In [9]:
df_encode = pd.get_dummies(df, columns=["quartier", "type"])
df_encode.head()

,titre,ville,surface,nb_chambres,nb_salons,nb_salles_de_bains,prix,quartier_Abobo,quartier_Adjamé,quartier_Bingerville,...,quartier_Koumassi,quartier_Marcory,quartier_Plateau,quartier_Port-Bouët,quartier_Treichville,quartier_Yopougon,type_appartement,type_maison,type_studio,type_villa
0,Studio à Cocody,Abidjan,26,0,1,1,120000,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,Studio à Marcory,Abidjan,39,0,1,1,155000,False,False,False,...,False,True,False,False,False,False,False,False,True,False
2,Studio à Adjamé,Abidjan,36,0,1,1,70000,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,Studio à Plateau,Abidjan,24,0,1,1,120000,False,False,False,...,False,False,True,False,False,False,False,False,True,False
4,Studio à Abobo,Abidjan,35,0,1,1,55000,True,False,False,...,False,False,False,False,False,False,False,False,True,False

In [7]:
X = df_encode.drop(columns=["titre", "ville", "prix"])
y = df_encode["prix"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape)

(800, 18) (200, 18)

In [10]:
model = RandomForestRegressor(n_estimators=200, random_state=42)
model.fit(X_train, y_train)
prediction = model.predict(X_test)
mae = mean_absolute_error(y_test, prediction)
r2 = r2_score(y_test, prediction)
print(f"Error moyenne absolute (MAE): {mae:,.0f}FCFA")
print(f"score R²: {r2:.3f}")

Error moyenne absolute (MAE): 41,468FCFA
score R²: 0.985

In [ ]:
joblib.dump(model, "modele_prix.joblib")
joblib.dump(X.columns.tolist(), "colonnes_modele.joblib")